// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one

INSERT INTO giki_wallet.employee_profiles(user_id, employee_id)
Values ($1, $2)
RETURNING user_id, employee_id, designation, department
`

type CreateEmployeeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EmployeeID string    `json:"employee_id"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (GikiWalletEmployeeProfile, error) {
	row := q.db.QueryRow(ctx, createEmployee, arg.UserID, arg.EmployeeID)
	var i GikiWalletEmployeeProfile
	err := row.Scan(
		&i.UserID,
		&i.EmployeeID,
		&i.Designation,
		&i.Department,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one

INSERT INTO giki_wallet.student_profiles(user_id, reg_id, batch_year)
VALUES ($1, $2, $3)
RETURNING user_id, reg_id, degree_program, batch_year
`

type CreateStudentParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	RegID     string      `json:"reg_id"`
	BatchYear pgtype.Int4 `json:"batch_year"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (GikiWalletStudentProfile, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.RegID, arg.BatchYear)
	var i GikiWalletStudentProfile
	err := row.Scan(
		&i.UserID,
		&i.RegID,
		&i.DegreeProgram,
		&i.BatchYear,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO giki_wallet.users(name, email, phone_number, auth_provider, password_hash, password_algo, is_active, is_verified, user_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, email, phone_number, auth_provider, external_id, password_hash, password_algo, is_active, is_verified, user_type, created_at, updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	AuthProvider string `json:"auth_provider"`
	PasswordHash string `json:"password_hash"`
	PasswordAlgo string `json:"password_algo"`
	IsActive     bool   `json:"is_active"`
	IsVerified   bool   `json:"is_verified"`
	UserType     string `json:"user_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (GikiWalletUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AuthProvider,
		arg.PasswordHash,
		arg.PasswordAlgo,
		arg.IsActive,
		arg.IsVerified,
		arg.UserType,
	)
	var i GikiWalletUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, name, email, phone_number, auth_provider, external_id, password_hash, password_algo, is_active, is_verified, user_type, created_at, updated_at FROM giki_wallet.users
WHERE giki_wallet.users.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GikiWalletUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GikiWalletUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
