// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_db

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (GikiWalletEmployeeProfile, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (GikiWalletStudentProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (GikiWalletUser, error)
	GetUserByEmail(ctx context.Context, email string) (GikiWalletUser, error)
}

var _ Querier = (*Queries)(nil)
