--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 16.8 (Debian 16.8-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_adminnotification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_adminnotification (
    id bigint NOT NULL,
    message text NOT NULL,
    notification_type character varying(25) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    reviewed_by_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_adminnotification OWNER TO postgres;

--
-- Name: authentication_adminnotification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_adminnotification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_adminnotification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    full_name character varying(100) NOT NULL,
    "regID" character varying(100),
    is_employee boolean NOT NULL,
    is_student boolean NOT NULL,
    is_approved boolean NOT NULL,
    password_reset_token character varying(255),
    password_reset_token_expires timestamp with time zone,
    account_activation_token character varying(255),
    account_activation_token_expires timestamp with time zone,
    password_change_required boolean NOT NULL,
    account_locked_until timestamp with time zone,
    failed_login_count integer NOT NULL,
    last_failed_login timestamp with time zone,
    employee_cnic character varying(13),
    phone character varying(15),
    account_activation_token_hint character varying(16),
    CONSTRAINT authentication_customuser_failed_login_count_check CHECK ((failed_login_count >= 0))
);


ALTER TABLE public.authentication_customuser OWNER TO postgres;

--
-- Name: authentication_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_groups OWNER TO postgres;

--
-- Name: authentication_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_user_permissions OWNER TO postgres;

--
-- Name: authentication_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_archiveaccesslog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_archiveaccesslog (
    id bigint NOT NULL,
    access_type character varying(20) NOT NULL,
    accessed_at timestamp with time zone NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    search_query character varying(200) NOT NULL,
    filters_applied jsonb NOT NULL,
    results_count integer,
    session_id character varying(40) NOT NULL,
    user_id bigint NOT NULL,
    route_archive_id bigint
);


ALTER TABLE public.base_archiveaccesslog OWNER TO postgres;

--
-- Name: base_archiveaccesslog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_archiveaccesslog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_archiveaccesslog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_complaint; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_complaint (
    id bigint NOT NULL,
    category character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    impact_level character varying(20) NOT NULL,
    urgency_level character varying(20) NOT NULL,
    ticket_number character varying(10),
    route_id character varying(50),
    transaction_ref character varying(100),
    contact_preference character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    priority integer NOT NULL,
    admin_notes text NOT NULL,
    resolution_notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    user_satisfaction integer,
    assigned_to_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.base_complaint OWNER TO postgres;

--
-- Name: base_complaint_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_complaint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_complaint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_complaintmessage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_complaintmessage (
    id bigint NOT NULL,
    message text NOT NULL,
    is_admin boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    complaint_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.base_complaintmessage OWNER TO postgres;

--
-- Name: base_complaintmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_complaintmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_complaintmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_driver; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_driver (
    id bigint NOT NULL,
    driver_name character varying(30) NOT NULL,
    driver_number integer NOT NULL
);


ALTER TABLE public.base_driver OWNER TO postgres;

--
-- Name: base_driver_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_driver ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_driver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_guestticketrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_guestticketrequest (
    id bigint NOT NULL,
    guest_name character varying(100) NOT NULL,
    guest_cnic character varying(15) NOT NULL,
    guest_relation character varying(20) NOT NULL,
    ticket_cost integer NOT NULL,
    status character varying(20) NOT NULL,
    approved_at timestamp with time zone,
    rejection_reason text NOT NULL,
    txn_ref_no character varying(50),
    payment_method character varying(20),
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    admin_approved_by_id bigint,
    created_ticket_id bigint,
    requester_id bigint NOT NULL,
    route_id bigint NOT NULL,
    requester_type character varying(20) NOT NULL
);


ALTER TABLE public.base_guestticketrequest OWNER TO postgres;

--
-- Name: base_guestticketrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_guestticketrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_guestticketrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_paymentverification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_paymentverification (
    id bigint NOT NULL,
    txn_ref_no character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    payment_method character varying(10) NOT NULL,
    verification_message text,
    created_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone NOT NULL,
    refund_amount integer,
    refunded_at timestamp with time zone,
    user_id bigint NOT NULL,
    route_id bigint NOT NULL,
    origin_domain character varying(20) NOT NULL,
    ticket_type character varying(20) NOT NULL,
    total_ticket_count integer NOT NULL,
    guest_payment_order integer,
    guest_ticket_id_id bigint,
    is_guest_payment boolean NOT NULL,
    guest_cnic character varying(15),
    guest_name character varying(100),
    student_ticket_type character varying(20) NOT NULL,
    archived_at timestamp with time zone,
    is_archived boolean NOT NULL,
    last_verification_attempt timestamp with time zone,
    verification_attempts integer DEFAULT 0 NOT NULL,
    verification_cache_until timestamp with time zone,
    idempotency_key character varying(100),
    reservation_deducted boolean NOT NULL,
    reservation_id integer,
    dropoff_stop character varying(150),
    pickup_stop character varying(150)
);


ALTER TABLE public.base_paymentverification OWNER TO postgres;

--
-- Name: base_paymentverification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_paymentverification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_paymentverification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_refundrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_refundrequest (
    id bigint NOT NULL,
    txn_ref_no character varying(100) NOT NULL,
    amount integer NOT NULL,
    status character varying(20) NOT NULL,
    response_code character varying(10),
    response_message text,
    created_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone,
    payment_verification_id bigint NOT NULL,
    archived_at timestamp with time zone,
    is_archived boolean NOT NULL
);


ALTER TABLE public.base_refundrequest OWNER TO postgres;

--
-- Name: base_refundrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_refundrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_refundrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_reservation (
    id integer NOT NULL,
    user_id integer NOT NULL,
    route_id integer NOT NULL,
    status character varying(10) DEFAULT 'held'::character varying NOT NULL,
    count integer DEFAULT 1 NOT NULL,
    idempotency_key character varying(100),
    expires_at timestamp with time zone NOT NULL,
    payment_verification_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.base_reservation OWNER TO postgres;

--
-- Name: base_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.base_reservation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.base_reservation_id_seq OWNER TO postgres;

--
-- Name: base_reservation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.base_reservation_id_seq OWNED BY public.base_reservation.id;


--
-- Name: base_route; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_route (
    id bigint NOT NULL,
    from_location character varying(20) NOT NULL,
    to_location character varying(20) NOT NULL,
    "bus_No" integer,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    pickup_location character varying(100),
    dropoff_location character varying(100),
    tickets integer NOT NULL,
    price integer NOT NULL,
    bus_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    archived_at timestamp with time zone,
    archive_reason character varying(200) NOT NULL,
    original_route_id character varying(50),
    is_template boolean NOT NULL,
    auto_archive_after_days integer NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    archived_by_id bigint,
    bus_driver_id bigint,
    capacity integer,
    CONSTRAINT route_capacity_non_negative CHECK ((capacity >= 0)),
    CONSTRAINT route_tickets_non_negative CHECK ((tickets >= 0)),
    CONSTRAINT route_tickets_not_exceed_capacity CHECK ((tickets <= capacity))
);


ALTER TABLE public.base_route OWNER TO postgres;

--
-- Name: base_route_allowed_employee_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_route_allowed_employee_groups (
    id bigint NOT NULL,
    route_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.base_route_allowed_employee_groups OWNER TO postgres;

--
-- Name: base_route_allowed_employee_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_route_allowed_employee_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_route_allowed_employee_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_route_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_route ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_route_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_routearchive; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_routearchive (
    id bigint NOT NULL,
    original_route_id integer NOT NULL,
    route_data jsonb NOT NULL,
    tickets_data jsonb NOT NULL,
    payments_data jsonb NOT NULL,
    archived_at timestamp with time zone NOT NULL,
    archive_reason character varying(200) NOT NULL,
    archive_type character varying(20) NOT NULL,
    route_hash character varying(64) NOT NULL,
    tickets_count integer NOT NULL,
    archive_status character varying(20) NOT NULL,
    is_compressed boolean NOT NULL,
    compression_ratio double precision,
    last_accessed_at timestamp with time zone,
    access_count integer NOT NULL,
    archived_by_id bigint
);


ALTER TABLE public.base_routearchive OWNER TO postgres;

--
-- Name: base_routearchive_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_routearchive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_routearchive_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_routestopoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_routestopoption (
    id integer NOT NULL,
    origin character varying(20) NOT NULL,
    destination character varying(20) NOT NULL,
    direction character varying(10) NOT NULL,
    name character varying(150) NOT NULL,
    sequence integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT base_routestopoption_sequence_check CHECK ((sequence >= 0))
);


ALTER TABLE public.base_routestopoption OWNER TO postgres;

--
-- Name: base_routestopoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_routestopoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_routestopoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.base_ticket (
    id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    "regID" character varying(20) NOT NULL,
    booked_at timestamp with time zone,
    txn_ref_no character varying(100),
    is_self boolean NOT NULL,
    is_employee_traveling boolean NOT NULL,
    relative_name character varying(255),
    relative_cnic character varying(15),
    relative_relation character varying(50),
    ticket_number character varying(10),
    is_archived boolean NOT NULL,
    archived_with_route boolean NOT NULL,
    archive_snapshot jsonb,
    ticket_status character varying(20) NOT NULL,
    archived_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancellation_reason character varying(200) NOT NULL,
    route_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_additional_ticket boolean NOT NULL,
    is_refunded boolean NOT NULL,
    refund_amount integer,
    requires_payment boolean NOT NULL,
    ticket_cost integer NOT NULL,
    guest_payment_order integer,
    guest_payment_status character varying(20) NOT NULL,
    ticket_category character varying(20) NOT NULL,
    guest_ticket_request_id bigint,
    route_date date,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL,
    route_serial integer,
    ticket_week character varying(8),
    dropoff_stop character varying(150),
    pickup_stop character varying(150)
);


ALTER TABLE public.base_ticket OWNER TO postgres;

--
-- Name: base_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.base_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_cron_cronjoblock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_cron_cronjoblock (
    id integer NOT NULL,
    job_name character varying(200) NOT NULL,
    locked boolean NOT NULL
);


ALTER TABLE public.django_cron_cronjoblock OWNER TO postgres;

--
-- Name: django_cron_cronjoblock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_cron_cronjoblock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_cron_cronjoblock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_cron_cronjoblog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_cron_cronjoblog (
    id integer NOT NULL,
    code character varying(64) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    is_success boolean NOT NULL,
    message text NOT NULL,
    ran_at_time time without time zone
);


ALTER TABLE public.django_cron_cronjoblog OWNER TO postgres;

--
-- Name: django_cron_cronjoblog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_cron_cronjoblog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_cron_cronjoblog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: login_attempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.login_attempts (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    ip_address inet NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    successful boolean NOT NULL,
    user_agent text NOT NULL,
    failure_reason character varying(100) NOT NULL
);


ALTER TABLE public.login_attempts OWNER TO postgres;

--
-- Name: login_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_reservation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation ALTER COLUMN id SET DEFAULT nextval('public.base_reservation_id_seq'::regclass);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_adminnotification authentication_adminnotification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_adminnotification
    ADD CONSTRAINT authentication_adminnotification_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_groups authentication_customuse_customuser_id_group_id_8a637646_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuse_customuser_id_group_id_8a637646_uniq UNIQUE (customuser_id, group_id);


--
-- Name: authentication_customuser_user_permissions authentication_customuse_customuser_id_permission_923704b1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuse_customuser_id_permission_923704b1_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: authentication_customuser authentication_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_email_key UNIQUE (email);


--
-- Name: authentication_customuser_groups authentication_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_user_permissions authentication_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: base_archiveaccesslog base_archiveaccesslog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_archiveaccesslog
    ADD CONSTRAINT base_archiveaccesslog_pkey PRIMARY KEY (id);


--
-- Name: base_complaint base_complaint_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaint
    ADD CONSTRAINT base_complaint_pkey PRIMARY KEY (id);


--
-- Name: base_complaintmessage base_complaintmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaintmessage
    ADD CONSTRAINT base_complaintmessage_pkey PRIMARY KEY (id);


--
-- Name: base_driver base_driver_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_driver
    ADD CONSTRAINT base_driver_pkey PRIMARY KEY (id);


--
-- Name: base_guestticketrequest base_guestticketrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_guestticketrequest
    ADD CONSTRAINT base_guestticketrequest_pkey PRIMARY KEY (id);


--
-- Name: base_paymentverification base_paymentverification_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverification_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: base_paymentverification base_paymentverification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverification_pkey PRIMARY KEY (id);


--
-- Name: base_paymentverification base_paymentverification_txn_ref_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverification_txn_ref_no_key UNIQUE (txn_ref_no);


--
-- Name: base_refundrequest base_refundrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_refundrequest
    ADD CONSTRAINT base_refundrequest_pkey PRIMARY KEY (id);


--
-- Name: base_refundrequest base_refundrequest_txn_ref_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_refundrequest
    ADD CONSTRAINT base_refundrequest_txn_ref_no_key UNIQUE (txn_ref_no);


--
-- Name: base_reservation base_reservation_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation
    ADD CONSTRAINT base_reservation_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: base_reservation base_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation
    ADD CONSTRAINT base_reservation_pkey PRIMARY KEY (id);


--
-- Name: base_route_allowed_employee_groups base_route_allowed_emplo_route_id_group_id_604d6fbb_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route_allowed_employee_groups
    ADD CONSTRAINT base_route_allowed_emplo_route_id_group_id_604d6fbb_uniq UNIQUE (route_id, group_id);


--
-- Name: base_route_allowed_employee_groups base_route_allowed_employee_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route_allowed_employee_groups
    ADD CONSTRAINT base_route_allowed_employee_groups_pkey PRIMARY KEY (id);


--
-- Name: base_route base_route_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route
    ADD CONSTRAINT base_route_pkey PRIMARY KEY (id);


--
-- Name: base_routearchive base_routearchive_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_routearchive
    ADD CONSTRAINT base_routearchive_pkey PRIMARY KEY (id);


--
-- Name: base_routestopoption base_routestopoption_origin_destination_direc_973b8616_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_routestopoption
    ADD CONSTRAINT base_routestopoption_origin_destination_direc_973b8616_uniq UNIQUE (origin, destination, direction, name);


--
-- Name: base_routestopoption base_routestopoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_routestopoption
    ADD CONSTRAINT base_routestopoption_pkey PRIMARY KEY (id);


--
-- Name: base_ticket base_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_ticket
    ADD CONSTRAINT base_ticket_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_cron_cronjoblock django_cron_cronjoblock_job_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblock
    ADD CONSTRAINT django_cron_cronjoblock_job_name_key UNIQUE (job_name);


--
-- Name: django_cron_cronjoblock django_cron_cronjoblock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblock
    ADD CONSTRAINT django_cron_cronjoblock_pkey PRIMARY KEY (id);


--
-- Name: django_cron_cronjoblog django_cron_cronjoblog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_cron_cronjoblog
    ADD CONSTRAINT django_cron_cronjoblog_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: login_attempts login_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_attempts
    ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);


--
-- Name: base_ticket uniq_ticket_per_week_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_ticket
    ADD CONSTRAINT uniq_ticket_per_week_number UNIQUE (ticket_week, ticket_number);


--
-- Name: base_ticket uniq_ticket_route_serial; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_ticket
    ADD CONSTRAINT uniq_ticket_route_serial UNIQUE (route_id, route_serial);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_adminnotification_reviewed_by_id_45c4355c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_adminnotification_reviewed_by_id_45c4355c ON public.authentication_adminnotification USING btree (reviewed_by_id);


--
-- Name: authentication_adminnotification_user_id_69251596; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_adminnotification_user_id_69251596 ON public.authentication_adminnotification USING btree (user_id);


--
-- Name: authentication_customuse_account_activation_token_faafa653_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuse_account_activation_token_faafa653_like ON public.authentication_customuser USING btree (account_activation_token_hint varchar_pattern_ops);


--
-- Name: authentication_customuser__customuser_id_33d2a5f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser__customuser_id_33d2a5f7 ON public.authentication_customuser_user_permissions USING btree (customuser_id);


--
-- Name: authentication_customuser__permission_id_e47332af; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser__permission_id_e47332af ON public.authentication_customuser_user_permissions USING btree (permission_id);


--
-- Name: authentication_customuser_account_activation_token_h_faafa653; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_account_activation_token_h_faafa653 ON public.authentication_customuser USING btree (account_activation_token_hint);


--
-- Name: authentication_customuser_email_a127f886_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_email_a127f886_like ON public.authentication_customuser USING btree (email varchar_pattern_ops);


--
-- Name: authentication_customuser_employee_cnic_0e7eb1c3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_employee_cnic_0e7eb1c3 ON public.authentication_customuser USING btree (employee_cnic);


--
-- Name: authentication_customuser_employee_cnic_0e7eb1c3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_employee_cnic_0e7eb1c3_like ON public.authentication_customuser USING btree (employee_cnic varchar_pattern_ops);


--
-- Name: authentication_customuser_groups_customuser_id_a7d1343c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_groups_customuser_id_a7d1343c ON public.authentication_customuser_groups USING btree (customuser_id);


--
-- Name: authentication_customuser_groups_group_id_c5ef1d10; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_groups_group_id_c5ef1d10 ON public.authentication_customuser_groups USING btree (group_id);


--
-- Name: base_archiv_access__51e167_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiv_access__51e167_idx ON public.base_archiveaccesslog USING btree (access_type, accessed_at);


--
-- Name: base_archiv_accesse_95b902_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiv_accesse_95b902_idx ON public.base_archiveaccesslog USING btree (accessed_at);


--
-- Name: base_archiv_ip_addr_4687d0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiv_ip_addr_4687d0_idx ON public.base_archiveaccesslog USING btree (ip_address, accessed_at);


--
-- Name: base_archiv_route_a_cab4b9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiv_route_a_cab4b9_idx ON public.base_archiveaccesslog USING btree (route_archive_id, accessed_at);


--
-- Name: base_archiv_user_id_89d94d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiv_user_id_89d94d_idx ON public.base_archiveaccesslog USING btree (user_id, accessed_at);


--
-- Name: base_archiveaccesslog_route_archive_id_1611d2f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiveaccesslog_route_archive_id_1611d2f7 ON public.base_archiveaccesslog USING btree (route_archive_id);


--
-- Name: base_archiveaccesslog_user_id_79d38a4d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_archiveaccesslog_user_id_79d38a4d ON public.base_archiveaccesslog USING btree (user_id);


--
-- Name: base_complaint_assigned_to_id_c02f4862; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_complaint_assigned_to_id_c02f4862 ON public.base_complaint USING btree (assigned_to_id);


--
-- Name: base_complaint_user_id_deee8b6d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_complaint_user_id_deee8b6d ON public.base_complaint USING btree (user_id);


--
-- Name: base_complaintmessage_complaint_id_92ada44e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_complaintmessage_complaint_id_92ada44e ON public.base_complaintmessage USING btree (complaint_id);


--
-- Name: base_complaintmessage_sender_id_75fd74d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_complaintmessage_sender_id_75fd74d1 ON public.base_complaintmessage USING btree (sender_id);


--
-- Name: base_guestticketrequest_admin_approved_by_id_c833ddc9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_guestticketrequest_admin_approved_by_id_c833ddc9 ON public.base_guestticketrequest USING btree (admin_approved_by_id);


--
-- Name: base_guestticketrequest_created_ticket_id_3eb606c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_guestticketrequest_created_ticket_id_3eb606c2 ON public.base_guestticketrequest USING btree (created_ticket_id);


--
-- Name: base_guestticketrequest_employee_id_ed5e2a06; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_guestticketrequest_employee_id_ed5e2a06 ON public.base_guestticketrequest USING btree (requester_id);


--
-- Name: base_guestticketrequest_route_id_fe7268b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_guestticketrequest_route_id_fe7268b2 ON public.base_guestticketrequest USING btree (route_id);


--
-- Name: base_paymen_origin__394f38_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymen_origin__394f38_idx ON public.base_paymentverification USING btree (origin_domain, created_at);


--
-- Name: base_paymen_origin__b177d4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymen_origin__b177d4_idx ON public.base_paymentverification USING btree (origin_domain, status);


--
-- Name: base_paymen_txn_ref_5d049f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymen_txn_ref_5d049f_idx ON public.base_paymentverification USING btree (txn_ref_no);


--
-- Name: base_paymen_user_id_c1e8b8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymen_user_id_c1e8b8_idx ON public.base_paymentverification USING btree (user_id, status);


--
-- Name: base_paymen_user_id_f88c90_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymen_user_id_f88c90_idx ON public.base_paymentverification USING btree (user_id, origin_domain);


--
-- Name: base_paymentver_reservation_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentver_reservation_id_idx ON public.base_paymentverification USING btree (reservation_id);


--
-- Name: base_paymentverification_guest_ticket_id_id_e60f3dca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_guest_ticket_id_id_e60f3dca ON public.base_paymentverification USING btree (guest_ticket_id_id);


--
-- Name: base_paymentverification_idempotency_key_739579b3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_idempotency_key_739579b3_like ON public.base_paymentverification USING btree (idempotency_key varchar_pattern_ops);


--
-- Name: base_paymentverification_idempotency_key_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX base_paymentverification_idempotency_key_unique ON public.base_paymentverification USING btree (idempotency_key) WHERE ((idempotency_key IS NOT NULL) AND ((idempotency_key)::text <> ''::text));


--
-- Name: base_paymentverification_origin_domain_25e3786a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_origin_domain_25e3786a ON public.base_paymentverification USING btree (origin_domain);


--
-- Name: base_paymentverification_origin_domain_25e3786a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_origin_domain_25e3786a_like ON public.base_paymentverification USING btree (origin_domain varchar_pattern_ops);


--
-- Name: base_paymentverification_route_id_aba5d81b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_route_id_aba5d81b ON public.base_paymentverification USING btree (route_id);


--
-- Name: base_paymentverification_txn_ref_no_06789760_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_txn_ref_no_06789760_like ON public.base_paymentverification USING btree (txn_ref_no varchar_pattern_ops);


--
-- Name: base_paymentverification_txn_ref_no_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX base_paymentverification_txn_ref_no_unique ON public.base_paymentverification USING btree (txn_ref_no);


--
-- Name: base_paymentverification_user_id_8d45cc71; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_paymentverification_user_id_8d45cc71 ON public.base_paymentverification USING btree (user_id);


--
-- Name: base_refundrequest_payment_verification_id_ae72e9c1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_refundrequest_payment_verification_id_ae72e9c1 ON public.base_refundrequest USING btree (payment_verification_id);


--
-- Name: base_refundrequest_txn_ref_no_9a5b6ab7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_refundrequest_txn_ref_no_9a5b6ab7_like ON public.base_refundrequest USING btree (txn_ref_no varchar_pattern_ops);


--
-- Name: base_reservation_payment_verification_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_reservation_payment_verification_idx ON public.base_reservation USING btree (payment_verification_id);


--
-- Name: base_route_allowed_employee_groups_group_id_3b61760d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_allowed_employee_groups_group_id_3b61760d ON public.base_route_allowed_employee_groups USING btree (group_id);


--
-- Name: base_route_allowed_employee_groups_route_id_f2e9c69f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_allowed_employee_groups_route_id_f2e9c69f ON public.base_route_allowed_employee_groups USING btree (route_id);


--
-- Name: base_route_archive_95cc49_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_archive_95cc49_idx ON public.base_route USING btree (archived_at);


--
-- Name: base_route_archived_by_id_5bc80242; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_archived_by_id_5bc80242 ON public.base_route USING btree (archived_by_id);


--
-- Name: base_route_bus_driver_id_b6684a5f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_bus_driver_id_b6684a5f ON public.base_route USING btree (bus_driver_id);


--
-- Name: base_route_bus_typ_734f0a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_bus_typ_734f0a_idx ON public.base_route USING btree (bus_type, status);


--
-- Name: base_route_bus_typ_aad3da_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_bus_typ_aad3da_idx ON public.base_route USING btree (bus_type, status, date);


--
-- Name: base_route_created_53bdb2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_created_53bdb2_idx ON public.base_route USING btree (created_at);


--
-- Name: base_route_from_lo_308410_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_from_lo_308410_idx ON public.base_route USING btree (from_location, to_location, date);


--
-- Name: base_route_status_7fa4fb_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_status_7fa4fb_idx ON public.base_route USING btree (status, date);


--
-- Name: base_route_tickets_d73420_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_route_tickets_d73420_idx ON public.base_route USING btree (tickets, status, date);


--
-- Name: base_routea_archive_1bf4bf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_archive_1bf4bf_idx ON public.base_routearchive USING btree (archived_by_id);


--
-- Name: base_routea_archive_a73659_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_archive_a73659_idx ON public.base_routearchive USING btree (archived_at);


--
-- Name: base_routea_archive_ef525b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_archive_ef525b_idx ON public.base_routearchive USING btree (archive_type, archive_status);


--
-- Name: base_routea_last_ac_8d0ee9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_last_ac_8d0ee9_idx ON public.base_routearchive USING btree (last_accessed_at);


--
-- Name: base_routea_origina_82e835_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_origina_82e835_idx ON public.base_routearchive USING btree (original_route_id);


--
-- Name: base_routea_tickets_1aa44a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routea_tickets_1aa44a_idx ON public.base_routearchive USING btree (tickets_count);


--
-- Name: base_routearchive_archived_by_id_103d0757; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_routearchive_archived_by_id_103d0757 ON public.base_routearchive USING btree (archived_by_id);


--
-- Name: base_ticket_booked__9bc418_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_booked__9bc418_idx ON public.base_ticket USING btree (booked_at);


--
-- Name: base_ticket_guest_ticket_request_id_910203e0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_guest_ticket_request_id_910203e0 ON public.base_ticket USING btree (guest_ticket_request_id);


--
-- Name: base_ticket_is_arch_655c3e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_is_arch_655c3e_idx ON public.base_ticket USING btree (is_archived, archived_at);


--
-- Name: base_ticket_is_dele_260aba_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_is_dele_260aba_idx ON public.base_ticket USING btree (is_deleted, deleted_at);


--
-- Name: base_ticket_route_date_9f4c66bd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_route_date_9f4c66bd ON public.base_ticket USING btree (route_date);


--
-- Name: base_ticket_route_i_0519ac_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_route_i_0519ac_idx ON public.base_ticket USING btree (route_id, ticket_status);


--
-- Name: base_ticket_route_id_557e0360; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_route_id_557e0360 ON public.base_ticket USING btree (route_id);


--
-- Name: base_ticket_ticket__d52a48_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_ticket__d52a48_idx ON public.base_ticket USING btree (ticket_category, ticket_status);


--
-- Name: base_ticket_ticket__f4ad8e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_ticket__f4ad8e_idx ON public.base_ticket USING btree (ticket_week, ticket_number);


--
-- Name: base_ticket_txn_ref_e38525_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_txn_ref_e38525_idx ON public.base_ticket USING btree (txn_ref_no);


--
-- Name: base_ticket_txn_ref_no_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX base_ticket_txn_ref_no_unique ON public.base_ticket USING btree (txn_ref_no) WHERE ((txn_ref_no IS NOT NULL) AND ((txn_ref_no)::text <> ''::text));


--
-- Name: base_ticket_user_id_052aef0f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_user_id_052aef0f ON public.base_ticket USING btree (user_id);


--
-- Name: base_ticket_user_id_21479f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_user_id_21479f_idx ON public.base_ticket USING btree (user_id, is_archived);


--
-- Name: base_ticket_user_id_c631a3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_user_id_c631a3_idx ON public.base_ticket USING btree (user_id, route_date, ticket_status);


--
-- Name: base_ticket_user_id_ed1ff3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX base_ticket_user_id_ed1ff3_idx ON public.base_ticket USING btree (user_id, ticket_status);


--
-- Name: base_ticket_user_route_date_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX base_ticket_user_route_date_unique ON public.base_ticket USING btree (user_id, route_id) WHERE (((ticket_status)::text = 'active'::text) AND (is_self = true));


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cron_cronjoblock_job_name_fb6ce879_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblock_job_name_fb6ce879_like ON public.django_cron_cronjoblock USING btree (job_name varchar_pattern_ops);


--
-- Name: django_cron_cronjoblog_code_48865653; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_48865653 ON public.django_cron_cronjoblog USING btree (code);


--
-- Name: django_cron_cronjoblog_code_48865653_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_48865653_like ON public.django_cron_cronjoblog USING btree (code varchar_pattern_ops);


--
-- Name: django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_is_success_ran_at_time_84da9606_idx ON public.django_cron_cronjoblog USING btree (code, is_success, ran_at_time);


--
-- Name: django_cron_cronjoblog_code_start_time_4fc78f9d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_start_time_4fc78f9d_idx ON public.django_cron_cronjoblog USING btree (code, start_time);


--
-- Name: django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_code_start_time_ran_at_time_8b50b8fa_idx ON public.django_cron_cronjoblog USING btree (code, start_time, ran_at_time);


--
-- Name: django_cron_cronjoblog_end_time_7918602a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_end_time_7918602a ON public.django_cron_cronjoblog USING btree (end_time);


--
-- Name: django_cron_cronjoblog_ran_at_time_7fed2751; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_ran_at_time_7fed2751 ON public.django_cron_cronjoblog USING btree (ran_at_time);


--
-- Name: django_cron_cronjoblog_start_time_d68c0dd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cron_cronjoblog_start_time_d68c0dd9 ON public.django_cron_cronjoblog USING btree (start_time);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_payment_user_status_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_user_status_created ON public.base_paymentverification USING btree (user_id, status, created_at);


--
-- Name: idx_payment_verification_status_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_verification_status_created ON public.base_paymentverification USING btree (status, created_at);


--
-- Name: idx_payment_verification_txn_ref; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_verification_txn_ref ON public.base_paymentverification USING btree (txn_ref_no);


--
-- Name: idx_payment_verification_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_verification_user_status ON public.base_paymentverification USING btree (user_id, status);


--
-- Name: idx_ticket_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ticket_category ON public.base_ticket USING btree (ticket_category);


--
-- Name: idx_ticket_user_route_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ticket_user_route_status ON public.base_ticket USING btree (user_id, route_id, ticket_status);


--
-- Name: idx_ticket_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ticket_user_status ON public.base_ticket USING btree (user_id, ticket_status);


--
-- Name: idx_user_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_active ON public.authentication_customuser USING btree (is_active);


--
-- Name: idx_user_email_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_email_active ON public.authentication_customuser USING btree (email, is_active);


--
-- Name: login_attem_email_ce49b0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX login_attem_email_ce49b0_idx ON public.login_attempts USING btree (email, "timestamp");


--
-- Name: login_attem_ip_addr_340a7c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX login_attem_ip_addr_340a7c_idx ON public.login_attempts USING btree (ip_address, "timestamp");


--
-- Name: reservation_route_status_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservation_route_status_idx ON public.base_reservation USING btree (route_id, status);


--
-- Name: reservation_status_exp_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reservation_status_exp_idx ON public.base_reservation USING btree (status, expires_at);


--
-- Name: uniq_employee_cnic_when_employee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_employee_cnic_when_employee ON public.authentication_customuser USING btree (employee_cnic) WHERE (is_employee AND (employee_cnic IS NOT NULL));


--
-- Name: unique_self_ticket_per_day_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_self_ticket_per_day_active ON public.base_ticket USING btree (user_id, route_date) WHERE (is_self AND ((ticket_status)::text = 'active'::text));


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_adminnotification authentication_admin_reviewed_by_id_45c4355c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_adminnotification
    ADD CONSTRAINT authentication_admin_reviewed_by_id_45c4355c_fk_authentic FOREIGN KEY (reviewed_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_adminnotification authentication_admin_user_id_69251596_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_adminnotification
    ADD CONSTRAINT authentication_admin_user_id_69251596_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_customuser_id_33d2a5f7_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_customuser_id_33d2a5f7_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_customuser_id_a7d1343c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_customuser_id_a7d1343c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_group_id_c5ef1d10_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_group_id_c5ef1d10_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_permission_id_e47332af_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_permission_id_e47332af_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_archiveaccesslog base_archiveaccesslo_route_archive_id_1611d2f7_fk_base_rout; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_archiveaccesslog
    ADD CONSTRAINT base_archiveaccesslo_route_archive_id_1611d2f7_fk_base_rout FOREIGN KEY (route_archive_id) REFERENCES public.base_routearchive(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_archiveaccesslog base_archiveaccesslo_user_id_79d38a4d_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_archiveaccesslog
    ADD CONSTRAINT base_archiveaccesslo_user_id_79d38a4d_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_complaint base_complaint_assigned_to_id_c02f4862_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaint
    ADD CONSTRAINT base_complaint_assigned_to_id_c02f4862_fk_authentic FOREIGN KEY (assigned_to_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_complaint base_complaint_user_id_deee8b6d_fk_authentication_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaint
    ADD CONSTRAINT base_complaint_user_id_deee8b6d_fk_authentication_customuser_id FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_complaintmessage base_complaintmessag_complaint_id_92ada44e_fk_base_comp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaintmessage
    ADD CONSTRAINT base_complaintmessag_complaint_id_92ada44e_fk_base_comp FOREIGN KEY (complaint_id) REFERENCES public.base_complaint(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_complaintmessage base_complaintmessag_sender_id_75fd74d1_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_complaintmessage
    ADD CONSTRAINT base_complaintmessag_sender_id_75fd74d1_fk_authentic FOREIGN KEY (sender_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_guestticketrequest base_guestticketrequ_admin_approved_by_id_c833ddc9_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_guestticketrequest
    ADD CONSTRAINT base_guestticketrequ_admin_approved_by_id_c833ddc9_fk_authentic FOREIGN KEY (admin_approved_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_guestticketrequest base_guestticketrequ_created_ticket_id_3eb606c2_fk_base_tick; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_guestticketrequest
    ADD CONSTRAINT base_guestticketrequ_created_ticket_id_3eb606c2_fk_base_tick FOREIGN KEY (created_ticket_id) REFERENCES public.base_ticket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_guestticketrequest base_guestticketrequ_requester_id_13637613_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_guestticketrequest
    ADD CONSTRAINT base_guestticketrequ_requester_id_13637613_fk_authentic FOREIGN KEY (requester_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_paymentverification base_paymentverifica_guest_ticket_id_id_e60f3dca_fk_base_tick; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverifica_guest_ticket_id_id_e60f3dca_fk_base_tick FOREIGN KEY (guest_ticket_id_id) REFERENCES public.base_ticket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_paymentverification base_paymentverifica_user_id_8d45cc71_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverifica_user_id_8d45cc71_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_paymentverification base_paymentverification_route_id_aba5d81b_fk_base_route_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_paymentverification
    ADD CONSTRAINT base_paymentverification_route_id_aba5d81b_fk_base_route_id FOREIGN KEY (route_id) REFERENCES public.base_route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_refundrequest base_refundrequest_payment_verification_ae72e9c1_fk_base_paym; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_refundrequest
    ADD CONSTRAINT base_refundrequest_payment_verification_ae72e9c1_fk_base_paym FOREIGN KEY (payment_verification_id) REFERENCES public.base_paymentverification(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_reservation base_reservation_payment_verification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation
    ADD CONSTRAINT base_reservation_payment_verification_id_fkey FOREIGN KEY (payment_verification_id) REFERENCES public.base_paymentverification(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_reservation base_reservation_route_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation
    ADD CONSTRAINT base_reservation_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.base_route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_reservation base_reservation_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_reservation
    ADD CONSTRAINT base_reservation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_route_allowed_employee_groups base_route_allowed_e_group_id_3b61760d_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route_allowed_employee_groups
    ADD CONSTRAINT base_route_allowed_e_group_id_3b61760d_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_route_allowed_employee_groups base_route_allowed_e_route_id_f2e9c69f_fk_base_rout; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route_allowed_employee_groups
    ADD CONSTRAINT base_route_allowed_e_route_id_f2e9c69f_fk_base_rout FOREIGN KEY (route_id) REFERENCES public.base_route(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_route base_route_archived_by_id_5bc80242_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route
    ADD CONSTRAINT base_route_archived_by_id_5bc80242_fk_authentic FOREIGN KEY (archived_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_route base_route_bus_driver_id_b6684a5f_fk_base_driver_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_route
    ADD CONSTRAINT base_route_bus_driver_id_b6684a5f_fk_base_driver_id FOREIGN KEY (bus_driver_id) REFERENCES public.base_driver(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: base_routearchive base_routearchive_archived_by_id_103d0757_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.base_routearchive
    ADD CONSTRAINT base_routearchive_archived_by_id_103d0757_fk_authentic FOREIGN KEY (archived_by_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

