// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GikiWalletAdmin struct {
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
}

type GikiWalletEmployeeProfile struct {
	UserID      uuid.UUID   `json:"user_id"`
	EmployeeID  string      `json:"employee_id"`
	Designation pgtype.Text `json:"designation"`
	Department  pgtype.Text `json:"department"`
}

type GikiWalletRefreshToken struct {
	ID              uuid.UUID        `json:"id"`
	TokenHash       string           `json:"token_hash"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	RevokedAt       pgtype.Timestamp `json:"revoked_at"`
	ReplacedByToken pgtype.Text      `json:"replaced_by_token"`
	DeviceInfo      pgtype.Text      `json:"device_info"`
	IpAddress       pgtype.Text      `json:"ip_address"`
	UserID          uuid.UUID        `json:"user_id"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type GikiWalletStudentProfile struct {
	UserID        uuid.UUID   `json:"user_id"`
	RegID         string      `json:"reg_id"`
	DegreeProgram pgtype.Text `json:"degree_program"`
	BatchYear     pgtype.Int4 `json:"batch_year"`
}

type GikiWalletUser struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	PasswordHash string      `json:"password_hash"`
	PasswordAlgo string      `json:"password_algo"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
