// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrentStatus string

const (
	CurrentStatusPENDING CurrentStatus = "PENDING"
	CurrentStatusSUCCESS CurrentStatus = "SUCCESS"
	CurrentStatusFAILED  CurrentStatus = "FAILED"
	CurrentStatusUNKNOWN CurrentStatus = "UNKNOWN"
)

func (e *CurrentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrentStatus(s)
	case string:
		*e = CurrentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrentStatus: %T", src)
	}
	return nil
}

type NullCurrentStatus struct {
	CurrentStatus CurrentStatus `json:"current_status"`
	Valid         bool          `json:"valid"` // Valid is true if CurrentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CurrentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrentStatus), nil
}

type GikiWalletAdmin struct {
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	Permissions []string  `json:"permissions"`
}

type GikiWalletEmployeeProfile struct {
	UserID      uuid.UUID   `json:"user_id"`
	EmployeeID  string      `json:"employee_id"`
	Designation pgtype.Text `json:"designation"`
	Department  pgtype.Text `json:"department"`
}

type GikiWalletGatewayTransaction struct {
	ID             uuid.UUID     `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	IdempotencyKey uuid.UUID     `json:"idempotency_key"`
	BillRefID      string        `json:"bill_ref_id"`
	TxnRefNo       string        `json:"txn_ref_no"`
	PaymentMethod  string        `json:"payment_method"`
	GatewayRrn     pgtype.Text   `json:"gateway_rrn"`
	Status         CurrentStatus `json:"status"`
	Amount         int64         `json:"amount"`
	RawResponse    []byte        `json:"raw_response"`
	IsPolling      pgtype.Bool   `json:"is_polling"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type GikiWalletRefreshToken struct {
	ID              uuid.UUID        `json:"id"`
	TokenHash       string           `json:"token_hash"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	RevokedAt       pgtype.Timestamp `json:"revoked_at"`
	ReplacedByToken pgtype.Text      `json:"replaced_by_token"`
	DeviceInfo      pgtype.Text      `json:"device_info"`
	IpAddress       pgtype.Text      `json:"ip_address"`
	UserID          uuid.UUID        `json:"user_id"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type GikiWalletStudentProfile struct {
	UserID        uuid.UUID   `json:"user_id"`
	RegID         string      `json:"reg_id"`
	DegreeProgram pgtype.Text `json:"degree_program"`
	BatchYear     pgtype.Int4 `json:"batch_year"`
}

type GikiWalletUser struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	PasswordHash string      `json:"password_hash"`
	PasswordAlgo string      `json:"password_algo"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
