// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package auth

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO giki_wallet.refresh_tokens(token_hash, expires_at, user_id)
VALUES ($1, $2, $3)
RETURNING id, token_hash, expires_at, revoked_at, replaced_by_token, device_info, ip_address, user_id, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    uuid.UUID        `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (GikiWalletRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.ExpiresAt, arg.UserID)
	var i GikiWalletRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByToken,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
