// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (GikiWalletRefreshToken, error)
}

var _ Querier = (*Queries)(nil)
